import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { serializeWith } from '../../core/codec-runtime.js'
import { serializeParams } from '../../core/params.js'
import type { ParamSpec } from '../../core/types.js'
import { type BuiltParam, toSpec } from '../builder.js'
import { c } from '../c.js'

/**
 * One of the two deliberate snapshots. Any diff in the generated
 * table is a MAJOR version bump, because it breaks links people have already shared.
 *
 * Regenerate with `pnpm api:update`; review the diff as the semver decision it is.
 */
// `fileURLToPath(new URL(...))` breaks here: happy-dom replaces the global `URL`, and node:url
// rejects the resulting object. Resolving from the module path as a string sidesteps it.
const FILE = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  '..',
  'api',
  'wire-format.md',
)

type Case = { codec: string; input: string; spec: ParamSpec<unknown>; value: unknown }

const row = <T>(codec: string, input: string, builder: BuiltParam<T>, value: T): Case =>
  ({ codec, input, spec: toSpec(builder) as ParamSpec<unknown>, value }) as Case

const CASES: readonly Case[] = [
  row('c.string()', "'hello'", c.string().default(''), 'hello'),
  row('c.string()', "'a b & c'", c.string().default(''), 'a b & c'),
  row('c.string()', "'日本語'", c.string().default(''), '日本語'),
  row('c.string()', "'a,b'", c.string().default(''), 'a,b'),
  row('c.string()', "'' (equals default)", c.string().default(''), ''),
  row('c.integer()', '42', c.integer().default(0), 42),
  row('c.integer()', '-7', c.integer().default(0), -7),
  row('c.float()', '1.5', c.float().default(0), 1.5),
  row('c.float()', '-0', c.float().default(1), -0),
  row('c.float()', 'NaN', c.float().default(0), Number.NaN),
  row('c.float()', 'Infinity', c.float().default(0), Number.POSITIVE_INFINITY),
  row('c.boolean()', 'true', c.boolean().default(false), true),
  row('c.boolean()', 'false', c.boolean().default(true), false),
  row('c.enum([...])', "'name'", c.enum(['created_at', 'name']).default('created_at'), 'name'),
  row('c.array(c.string())', "['a', 'b']", c.array(c.string()).default([]), ['a', 'b']),
  row('c.array(c.string())', "['a,b']", c.array(c.string()).default([]), ['a,b']),
  row('c.array(c.string())', "['a%2Cb']", c.array(c.string()).default([]), ['a%2Cb']),
  row('c.array(c.string())', "['']", c.array(c.string()).default([]), ['']),
  row('c.array(c.string())', '[] (empty)', c.array(c.string()).default(['x']), []),
  row('c.array(c.integer())', '[1, 2, 3]', c.array(c.integer()).default([]), [1, 2, 3]),
  row(
    "c.array(c.string(), { mode: 'repeat' })",
    "['a', 'b']",
    c.array(c.string(), { mode: 'repeat' }).default([]),
    ['a', 'b'],
  ),
  row(
    "c.array(c.string(), { sep: '|' })",
    "['a', 'b']",
    c.array(c.string(), { sep: '|' }).default([]),
    ['a', 'b'],
  ),
  row('c.isoDate()', 'new Date(0)', c.isoDate().default(new Date(1)), new Date(0)),
  row('c.timestamp()', 'new Date(0)', c.timestamp().default(new Date(1)), new Date(0)),
  row('c.json()', '{ a: 1, b: [2] }', c.json<unknown>().default(null), { a: 1, b: [2] }),
  row('c.numberRange()', '[10, 250]', c.numberRange().default([0, 0]), [10, 250]),
  row('c.numberRange()', '[-5, 10]', c.numberRange().default([0, 0]), [-5, 10]),
]

function render(): string {
  const lines = [
    '# Wire format',
    '',
    '<!-- GENERATED by `pnpm api:update`. Do not edit.',
    '     ANY diff in this table is a MAJOR version bump: it breaks links people already',
    '     shared. -->',
    '',
    'Every row is `?v=<query>` for a param named `v`. An empty query means the param is omitted.',
    '',
    '| Codec | Input | Query string |',
    '| --- | --- | --- |',
  ]
  for (const testCase of CASES) {
    const raw = serializeWith(testCase.spec, testCase.value)
    const params = new URLSearchParams()
    if (typeof raw === 'string') params.append('v', raw)
    else if (raw !== undefined) for (const value of raw) params.append('v', value)
    const query = serializeParams(params)
    lines.push(
      `| \`${testCase.codec}\` | \`${testCase.input}\` | ${query === '' ? '_(omitted)_' : `\`${query}\``} |`,
    )
  }
  return `${lines.join('\n')}\n`
}

describe('wire format', () => {
  it('matches the frozen snapshot', () => {
    const next = render()
    if (process.env.UPDATE_WIRE_FORMAT === '1') {
      writeFileSync(FILE, next)
      return
    }
    expect(existsSync(FILE)).toBe(true)
    expect(readFileSync(FILE, 'utf8')).toBe(next)
  })
})
